services:
  build-container:
    image: halversondm/my-dev-env:1.2.0
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 8080:8080
    volumes:
      - ~/dev:/development
      - devuser:/home/devuser
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  devuser: { }
  db: { }