name: dev-env
services:
  java-javascript:
    image: halversondm/my-dev-env:1.0.0
    privileged: true
    restart: always
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 8080:8080
    volumes:
      - ~/dev:/development
      - devuser:/home/devuser
      - /var/run/docker.sock:/var/run/docker.sock
  python:
    image: halversondm/my-python-env:1.1.0
    ports:
      - 6000:5000
      - 8888:8888
    volumes:
      - ~/dev:/development
      - venv:/home/devuser
  postgres:
    image: 'bitnami/postgresql:15'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=devuser
      - POSTGRESQL_PASSWORD=example
      - POSTGRESQL_DATABASE=devuser
volumes:
  devuser: { }
  postgres_data: { }
  venv: { }