services:
  java-javascript:
    image: halversondm/my-dev-env:1.4.0
    tty: true
    command: /bin/zsh
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 8080:8080
    volumes:
      - ~/dev:/development
      - devuser:/home/devuser
  python:
    image: halversondm/my-python-env:1.0.0
    environment:
      - OPENAI_API_KEY=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
      - LLAMA_INDEX_CACHE_DIR=/development/code/learning/llama-index
    ports:
      - 6000:5000
    volumes:
      - ~/dev:/development
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  devuser: { }
  db: { }